swagger: '2.0'
info:
  title: "erGW API"
  version: "1.0.0"
  description: "erGW API to interact with erGW"
  license:
    name: "GPL 2.0"
    url: "https://www.gnu.org/licenses/#GPL"
basePath: /api/v1
paths:
  /version:
    get:
      summary: get the erGW version
      responses:
        '200':
          description: 'returns version of the erGW'
          schema:
            $ref: '#/definitions/Version'
  /status:
    get:
      summary: get the status
      responses:
        '200':
          description: returns the current status
          schema:
            $ref: '#/definitions/Status'
  /status/accept-new:
    get:
      summary: get the current 'accept-new' status
      responses:
        '200':
          description: get the current 'accept-new' status
          schema:
            $ref: '#/definitions/StatusAcceptNewRequests'
  /status/accept-new/{value}:
    post:
      summary: 'enables/disables accepting new requests'
      parameters:
        - name: value
          in: path
          required: true
          type: boolean
          description: 'true - accept new requests, false - do not accept new requests'
      responses:
        '200':
          description: returns the current 'accept-new' status
          schema:
            $ref: '#/definitions/StatusAcceptNewRequests'
  /metrics:
    get:
      summary: get the metrics
      responses:
        '200':
          description: returns the metrics
  /redirector:
    get:
      summary: get list of the GTP Redirector sockets
      responses:
        '200':
          description: returns the list of all configured GTP Redirector sockets
          schema:
            type: "array"
            items:
              $ref: '#/definitions/RedirectorNode'
  /redirector/{name}:
    get:
      summary: get info about given GTP Redirector socket
      parameters:
        - name: name
          in: path
          required: true
          type: string
          description: 'the name of socket'
      responses:
        '200':
          description: returns all info about the given GTP Redirector socket
          schema:
            $ref: '#/definitions/RedirectorNode'
        '404':
          description: there is not GTP Redirector socket with given name
    put:
      summary: update the given GTP Redirector socket
      parameters:
        - name: name
          in: path
          required: true
          type: string
          description: 'the name of socket'
        - name: nodes
          in: body
          required: true
          schema:
            type: "array"
            items:
              $ref: '#/definitions/RedirectorNode'
      responses:
        '202':
          description: successful updated
        '404':
          description: there is not GTP Redirector socket with given name
        '400':
          description: wrong nodes list in the request
definitions:
  Status:
    type: "object"
    properties:
      acceptNewRequests:
        type: "boolean"
        default: true
      plmnId:
        $ref:
          "#/definitions/PLMN"
  PLMN:
    type: "object"
    properties:
      mcc:
        type: "string"
      mnc:
        type: "string"
  StatusAcceptNewRequests:
    type: "object"
    properties:
      acceptNewRequests:
        type: "boolean"
  Version:
    type: "object"
    properties:
      version:
        type: "string"
  RedirectorNode:
    type: "object"
    properties:
      ip:
        type: "string"
      port:
        type: "integer"
      version:
        type: "string"
        enum: 
          - v1
          - v2
